"""currencies table

Revision ID: e6add6d6c081
Revises: 21cc80a0c7b1
Create Date: 2018-07-15 21:50:27.729595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6add6d6c081'
down_revision = '21cc80a0c7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=True)
    op.create_index(op.f('ix_currency_symbol'), 'currency', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_symbol'), table_name='currency')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
